export const gamesData = [
  { id: 1, title: 'Elden Ring', tags: ['RPG', '액션', 'Open World'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg' },
  { id: 2, title: 'Cyberpunk 2077', tags: ['RPG', '액션', 'Sci-fi'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg' },
  { id: 3, title: "Baldur's Gate 3", tags: ['RPG', '전략', 'Turn-Based'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1086940/header.jpg' },
  { id: 4, title: 'Hades II', tags: ['액션', '인디', 'Roguelike'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1145350/header.jpg' },
  { id: 5, title: 'Helldivers 2', tags: ['액션', 'FPS', 'Co-op'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/553850/header.jpg' },
  { id: 6, title: 'Stardew Valley', tags: ['시뮬레이션', '인디', '캐주얼'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg' },
  { id: 7, title: 'Palworld', tags: ['액션', '어드벤처', 'Survival'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1623730/header.jpg' },
  { id: 8, title: 'Monster Hunter: World', tags: ['액션', 'RPG', 'Hunting'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/582010/header.jpg' },
  { id: 9, title: 'Cities: Skylines II', tags: ['전략', '시뮬레이션'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/949230/header.jpg' },
  { id: 10, title: 'Forza Horizon 5', tags: ['레이싱', '스포츠', 'Open World'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1551360/header.jpg' },
  { id: 11, title: 'Dota 2', tags: ['전략', '액션', 'MOBA'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/570/header.jpg' },
  { id: 12, title: 'EA SPORTS FC 24', tags: ['스포츠', '캐주얼'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/2124490/header.jpg' },
  { id: 13, title: 'Counter-Strike 2', tags: ['액션', 'FPS', 'Tactical'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/730/header.jpg' },
  { id: 14, title: 'Apex Legends', tags: ['액션', 'FPS', 'Battle Royale'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1172470/header.jpg' },
  { id: 15, title: 'The Witcher 3: Wild Hunt', tags: ['RPG', '액션', 'Open World'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg' },
  { id: 16, title: 'Sekiro: Shadows Die Twice', tags: ['액션', 'RPG', 'Souls-like'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/814380/header.jpg' },
  { id: 17, title: 'Red Dead Redemption 2', tags: ['액션', '어드벤처', 'Open World'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1174180/header.jpg' },
  { id: 18, title: 'Sid Meier’s Civilization VI', tags: ['전략', '시뮬레이션', 'Turn-Based'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/289070/header.jpg' },
  { id: 19, title: 'Rust', tags: ['액션', '어드벤처', 'Survival'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/252490/header.jpg' },
  { id: 20, title: 'Warframe', tags: ['액션', 'RPG', 'Looter Shooter'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/230410/header.jpg' },
  { id: 21, title: 'Destiny 2', tags: ['액션', 'FPS', 'RPG'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1085660/header.jpg' },
  { id: 22, title: 'Valheim', tags: ['액션', '어드벤처', 'Survival'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/892970/header.jpg' },
  { id: 23, title: 'Hollow Knight', tags: ['액션', '인디', 'Metroidvania'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/367520/header.jpg' },
  { id: 24, title: 'Terraria', tags: ['인디', '어드벤처', 'Sandbox'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/105600/header.jpg' },
  { id: 25, title: 'Grand Theft Auto V', tags: ['액션', '어드벤처', 'Open World'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/271590/header.jpg' },
  { id: 26, title: 'Portal 2', tags: ['어드벤처', '퍼즐'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/620/header.jpg' },
  { id: 27, title: 'Factorio', tags: ['전략', '시뮬레이션', '인디'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/427520/header.jpg' },
  { id: 28, title: 'RimWorld', tags: ['전략', '시뮬레이션', '인디'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/294100/header.jpg' },
  { id: 29, title: 'Project Zomboid', tags: ['시뮬레이션', '인디', 'Survival'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/108600/header.jpg' },
  { id: 30, title: 'Dead by Daylight', tags: ['액션', '공포'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/381210/header.jpg' },
  { id: 31, title: 'Rainbow Six Siege', tags: ['액션', 'FPS', 'Tactical'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/359550/header.jpg' },
  { id: 32, title: 'Team Fortress 2', tags: ['액션', 'FPS', 'Free to Play'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/440/header.jpg' },
  { id: 33, title: 'Overwatch 2', tags: ['액션', 'FPS', 'Hero Shooter'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/2357570/header.jpg' },
  { id: 34, title: 'PUBG: BATTLEGROUNDS', tags: ['액션', 'FPS', 'Battle Royale'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/578080/header.jpg' },
  { id: 35, title: 'Call of Duty', tags: ['액션', 'FPS', 'Shooter'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1938090/header.jpg' },
  { id: 36, title: 'Final Fantasy VII Rebirth', tags: ['RPG', '액션', 'Open World'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/2124510/header.jpg' },
  { id: 37, title: 'Dragon\'s Dogma 2', tags: ['RPG', '액션', 'Open World'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/2054970/header.jpg' },
  { id: 38, title: 'Street Fighter 6', tags: ['액션', '스포츠', 'Fighting'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1364780/header.jpg' },
  { id: 39, title: 'Tekken 8', tags: ['액션', '스포츠', 'Fighting'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1778820/header.jpg' },
  { id: 40, title: 'Hearts of Iron IV', tags: ['전략', '시뮬레이션', 'Wargame'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/394360/header.jpg' },
  { id: 41, title: 'Europa Universalis IV', tags: ['전략', '시뮬레이션', 'Grand Strategy'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/236850/header.jpg' },
  { id: 42, title: 'Crusader Kings III', tags: ['전략', '시뮬레이션', 'RPG'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1158310/header.jpg' },
  { id: 43, title: 'Microsoft Flight Simulator', tags: ['시뮬레이션', 'Open World'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1250410/header.jpg' },
  { id: 44, title: 'Satisfactory', tags: ['시뮬레이션', '전략', '인디'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/526870/header.jpg' },
  { id: 45, title: 'Phasmophobia', tags: ['공포', '인디', 'Co-op'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/739630/header.jpg' },
  { id: 46, title: 'Left 4 Dead 2', tags: ['액션', 'FPS', 'Zombies'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/550/header.jpg' },
  { id: 47, title: 'Borderlands 3', tags: ['액션', 'FPS', 'Looter Shooter'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/397540/header.jpg' },
  { id: 48, title: 'Persona 5 Royal', tags: ['RPG', 'Turn-Based', 'Anime'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/1687950/header.jpg' },
  { id: 49, title: 'Dark Souls III', tags: ['액션', 'RPG', 'Souls-like'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/374320/header.jpg' },
  { id: 50, title: 'War Thunder', tags: ['액션', '시뮬레이션', 'Free to Play'], image: 'https://cdn.akamai.steamstatic.com/steam/apps/236390/header.jpg' },
];

export const categories = [
  '전체', 'RPG', 'FPS', '전략', '시뮬레이션', '인디', 
  '액션', '어드벤처', '캐주얼', '스포츠', '레이싱'
];
